#pragma once
#define MASTER_LEFT

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define ONESHOT_TAP_TOGGLE 5 
#define ONESHOT_TIMEOUT 5000

#define TAPPING_FORCE_HOLD
#define HOLD_ON_OTHER_KEYPRESS
#define PERMISSIVE_HOLD 
#define TAPPING_TERM 150
