#pragma once
#define MASTER_RIGHT

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define ONESHOT_TAP_TOGGLE 5 
#define ONESHOT_TIMEOUT 1000

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define RETRO_TAPPING 
#define TAPPING_TERM 185
